package ru.otus.main_patterns.hw06;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.otus.main_patterns.hw06.codegen.GenerateHello;

/*
  Курс: Otus - Архитектура и шаблоны проектирования
   Занятия:
   13. Адаптер и мост

   Домашнее задание:
   Генерация адаптеров по интерфейсу

   Цель:
   В рамках данного ДЗ Вы научитесь генерировать адаптеры для интерфейсов, полученных при применении принципа DIP.
   ДЗ демонстрирует применение метапрограммирования для решения рутинных задач,
   а также возможности Reflection и компиляции "на лету" современных языков программирования.

   Если задание выполняется на C++, то задание заключается в написании препроцессора,
   который ищет абстрактные классы и по ним генерирует код адаптера, который включается в состав проекта.
   Для удобства такой препроцессор стоит запускать на этапе, предшествующем компиляции в процессе сборки,
   а также стоит подумать об удалении всех сгенерированных файлов при выполнении команды clear.

   Описание/Пошаговая инструкция выполнения домашнего задания:
   Предположим, что у нас есть интерфейс

   interface Spaceship.Operations.IMovable
   {
     Vector getPosition();
     void setPosition(Vector newValue);
     Vector getVelocity();
   }

   1. Необходимо по нему сгенерировать следующий класс:

       class AutoGenerated.MovableAdapter:  Spaceship.Operations.IMovable
       {
         UObject obj;
         public  MovableAdapter(UObject obj)
         {
            this.obj = obj;
         }

         public Vector getPosition()
         {
            return IoC.Resolve<Vector>("Spaceship.Operations.IMovable:position.get", obj);
         }

         public Vector getVelocity()
         {
            return IoC.Resolve<Vector>("Spaceship.Operations.IMovable:velocity.get", obj);
         }

         public void setPosition(Vector newValue)
         {
            IoC.Resolve<ICommand>("Spaceship.Operations.IMovable:position.set", obj, newValue).Execute();
         }
       }

   так, чтобы можно было создавать экземпляры этого класса.

   2. Экземпляры генерируемых оберток для объекта obj можно создавать следующей строкой:
       var adapter = IoC.Resolve<IMovable>("Adapter", typeof(IMovable), obj);

   3. Необязательная задача на подумать: если интерфейсу потребуются какие-либо методы, например, как
       interface Spaceship.Operations.IMovable
       {
         Vector getPosition();
         Vector setPosition(Vector newValue);
         Vector getVelocity();

         void finish();
       }

   Придумать реализацию адаптера для подобных методов.

   Критерии оценки:
   1. Задание сдано на проверку - 1 балл
   2. Реализован генератор адаптеров - 3 балла
   3. Реализованы тесты на генератор адаптеров - 2 балл
   4. Определена стратегия для IoC из п.2 задания - 2 балла
   5. Обработан случай из п.3 задания - 2 балла

   Решение:
   JavaPoet - библиотека генерации кода.
   Когда вы используете JavaPoet (например, для генерации адаптеров в игровом движке),
   вы переносите ошибки с этапа выполнения (Runtime) на этап компиляции (Compile-time).
   Если в вашей логике генерации что-то не так, проект просто не соберется, и вы сразу об этом узнаете.

   Главные фишки: зачем он нужен?
    -Управление импортами: Вам не нужно думать, какие import добавить в начало файла.
       Вы просто указываете тип класса (например, java.util.List), и JavaPoet сам добавит нужный импорт или использует полное имя,
       если возникнет конфликт.
    -Типобезопасность: Библиотека гарантирует, что вы не забудете закрыть скобку, поставите точку с запятой
       и правильно расположите модификаторы (public static final).
    -Форматирование: Сгенерированный код выглядит так, будто его написал человек: с правильными отступами,
       переносами строк и комментариями (Javadoc).

     Генератор кода: /processor/src/main/java/ru/otus/main_patterns/hw06/codegen
     Сгенерированный код: app/build/generated/sources/annotationProcessor/java/main
*/
@GenerateHello
public class HW06 {

  private static final Logger logger = LoggerFactory.getLogger(HW06.class);

  public static void main(String[] args) {
    logger.info(
        "Java version: {}, Java vendor: {}\nДомашнее задание #06: Генерация адаптеров по интерфейсу",
        System.getProperty("java.version"),
        System.getProperty("java.vendor"));

    // HelloGenerated.sayHello(); // <-- вызов сгенерированного метода
  }
}
